# Cloudflare Pages Build Log
# 2026-02-16T23:52:23.625Z	Initializing build environment...
# 2026-02-16T23:52:26.049Z	Success: Finished initializing build environment
# 2026-02-16T23:52:26.911Z	Cloning repository...
# 2026-02-16T23:52:30.646Z	No build output detected to cache. Skipping.
# 2026-02-16T23:52:30.646Z	No dependencies detected to cache. Skipping.
# 2026-02-16T23:52:30.649Z	Detected the following tools from environment: bun@1.2.15, nodejs@22.16.0

name = "scarygamesai"
compatibility_date = "2026-02-16"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[env.production]
name = "scarygamesai"

[env.preview]
name = "scarygamesai-preview"
